### ISSUE TITLE
Z80asm: Illegal Z80 'OUT (n), C' instruction not flagged as such, but interpreted as another instruction.

### ISSUE THREAD

**Issue by electrickery** [udo-munk/z80pack#117]
The Z80pack/z80asm program is my favorite for generating code for the MPF-I. Recently I found a 'convenient' but non-existing instruction is translated to another instruction, instead of being flagged as error. I found it in version 1.8, but the git-pulled version 1.9 behaves the same.

This is a line from the *.lis file:

`20e6  d3 81          261    261         OUT     (R_DATA), C  ; data out`

 d3 81  is 'OUT (81h), A'. As there is no error message, it took a while before I found 'OUT (n), C' does not exist. 'OUT (n)' behaves the same, and explains the behaviour, when assuming the ', A' is optional.

My hardware platform is MX-Linux x64 19.10 LTS. The program is called as 'z80asm -fh -oasmFile -l asmFile.asm'

Fred Jan

**Comment by udo-munk** [comment]
Hello Fred Jan,

interesting, over the time the assembler got some improvements so that it can assemble the unmodified MPF-1 monitor source,
some people were interested in this and I also still have my MPF-1.

I had a look at the sources, for OUT (n) no further checks are done, it simply assumes OUT (a),A because this is the
only valid instruction. I’ll add more checks for the correct instruction and flag something like you reported as error.
Guess I was to lazy for that back then and didn’t imagine that someone would try something like this.

Thanks and best regards,
Udo

**Comment by udo-munk** [comment]
fixed
