### ISSUE TITLE
RETI instruction

### ISSUE THREAD

**Issue by sneakywumpus** [udo-munk/z80pack#139]
While reading "The Undocumented Z80 Documented" I stumbled upon the statement that
RETI is exactly like RETN (i.e. copies IFF2 to IFF1) and only the Z80 PIO recognizes the RETI
opcode on the bus, and reacts to it. I looked at various other emulators (MAME, YAZE, FUSE, AltairZ80)
and they all treat RETI like RETN, sometimes don't even use the mnemonic RETI.
Z80SIM seems to be the only emulator that doesn't copy IFF2 to IFF! for the RETI opcode.
I don't know really much about Z80 interrupts and devices, just wanted to mention this.

**Comment by udo-munk** [comment]
The document doesn't say which Z80 behaves as described, there have been many from Zilog, Mostek, NEC, Hitachi etc. etc. besides other unlicensed reverse engineered ones, and all this stuff does behave different. When you do some more research you can find that even Z80 CPU's from Russia were used for testing. Of course this processors are OK for serious application usage, but they were of course not using the Zilog mask and so this behaves slightly different.

Yes, most emulator authors use this document as authorative and implement just what it says without questioning.

Way back then I experimented with RETN vs RETI, I was using all Mostek parts, because those passed our regressions tests at work, while Zilog parts did not. I wasn't interested much in the PIO, just using that for driving printers and plotters. Much more interesting were the SIO, CTC and DMA. The Mostek parts all recognized the RETI instruction. One can use RETN, but then has to clean the interrupt status in the chips one self, so that they accept the next interrupt. I do remember that in critical software we cleaned interrupt status in external chips our self anyway, just to make sure.

That handling of IFF1 and 2 must be done as decribed in the Zilog documentation, because if not some interrupt condition will not work as documented. If it works or not depends on the CPU vendor, if I remember correct the Mostek parts did exactly what was documented.

If you want a definitive answer get CPU and CTC from several vendors, put them on breadboards and test. The Z80 architecture uses daisy chained interrupt lines, so you need at least 2 sources for the interrupts to test everything in detail.

**Comment by udo-munk** [comment]
BTW, when Zilog put the Z80 into production demand was way more than what they were able to fabricate. So they needed another factory, Mostek was choosen for the second source production. So Mostek got the original mask from Zilog and in the beginning produced 100% identical chips.
The first versions had several problems, which were corrected with mask revisions. For some reason Zilog stopped correcting bugs at some time, while Mostek continued to do that. A Mostek Z80 with mask revision >= 5 will be different from any Zilog mask revision. So if anyone wants to get into this you need to care about the mask revision bedides the vendor also.

**Comment by sneakywumpus** [comment]
Thank you for explaining. I'll won't touch bus and interrupt code since I've never worked with the Z80 at the hardware level.
