### ISSUE TITLE
AT modem not working when compiled for Debian 12 / Linux Mint 21

### ISSUE THREAD

**Issue by zompiexx** [udo-munk/z80pack#268]
Hi Udo:

First of all, thanks so much for all your hard work on this great software :)

Whilst I have the AT modem working fine on my Mac Pro (running Mac OS Ventura), when I compile the same source code on a Linux Mint 21 or Debian 12 machine, the AT modem doesn't respond to AT commands. I have also tested this with the latest 1.38-dev build and have the same issue.

Also, whilst the 3D animation for the Imsaisim works fine on the Mac Pro, it isn't working on my Linux Mint 21 machine. Not a major problem as I can run as 2D, but would be good to get it working.

Perhaps I've missed some dependencies?

Any suggestions?

Best regards,

Andy

**Comment by udo-munk** [comment]
Sorry for the late answer, but I'm very busy.

I'm pretty sure that modem and graphics are OK, just works on OSX.

On Linux systems it is like works... works not... and so on after almost every update. The problems are in the Linux runtime somewhere, something gets broken, then fixed, then broken again ...
I'm not going to waste time with this, just using OSX and all is good.

Probably there are more stable Linux versions, like the commercial distributions, where this might be better, but you'll have to find out self.

So closing this for now because I think it is not an issue with the code here.
