### ISSUE TITLE
Add macros to z80asm

### ISSUE THREAD

**Issue by udo-munk** [udo-munk/z80pack#27]
Priority: low because one always can run some UNIX macro processor as front end
Difficulty: medium - difficult

Carfully study the modularity of this assembler. Have a look how the expression parser was replaced with a totally different one without any changes to other parts of the thing.
Implement a macro processor the same way, so that it can be substituted by another one
without modifying other parts. There have been quite some different macro implementations and eveyone prefers another one. To name a few:

Macro implementation by Digital Research in MAC/RMAC
Macro implementation by Microsoft in M80
Mostek had a very powerfull Macro processor in their UNIX cross assembler
Of course feel free to implement your own macro language.

Contributions will only be accepted if the macro processor can be substituted without
to much changes in the other components.

+++ for implementing two versions that can be selected with a command line option.

**Comment by sneakywumpus** [comment]
Is there manual for the Mostek assembler available? I've looked and found only
a "MOSTEK MACRO-80 ASSEMBLER V2.0" manual from 1979 on bitsavers.org.
That one looks really strange, more like FORTRAN with the .AND., .LT. etc.

**Comment by udo-munk** [comment]
I never found a manual for the Mostek cross assembler we were using on UNIX systems, too bad I didn't take a copy back then.
The Mostek assembler manuals on bitsavers.org are for the versions used on the Mostek development systems. I had a brief look at it, it is different.

**Comment by sneakywumpus** [comment]
Implemented in #193 and #194.

The implementation was done mostly looking at the Intel 8080/8085 Assembly Language
Programming manual from 1981 and the Digital Research MAC manual from 1980.

I use the `^` escape character from MAC, instead of the `!` that Intel uses. IFB, IFNB,
IFIDN, and IFDIF from M80 are also implemented.

The interface to the assembler consists of 2 variables and 6 functions:
Variables:
`mac_def_nest`: the current macro definition nesting level.
`mac_exp_nest`: the current macro expansion nesting level.
Functions:
`mac_start_pass` and `mac_end_pass`: to be called at start and end of a assembler pass.
`mac_add_line`: to add a line to a macro, to be called if `mac_def_nest > 0`.
`mac_expand`: to get a macro expansion line, to be called while `mac_exp_nest > 0`.
`mac_lookup`: and `mac_call` to search the macro table and start expanding a macro.

**Comment by sneakywumpus** [comment]
This took much more time and effort than the `.PHASE` implementation...
The difficulty ratings seem to be somewhat arbitrary :-)

**Comment by udo-munk** [comment]
Well, the difficulty rating just was a guess what might to get done for implementation.
Can this be closed or do you want to go further with the macros?

**Comment by sneakywumpus** [comment]
The implementation is basically done. Just some finer points in parameter passing (double string delimiter reduction,
for example) and dummy/local expansion. Every assembler seems to behave slightly different there.
My code currently behaves like DRI MAC, except that MAC seems to do the dummy/local expansion in multiple passes,
but that is perhaps a topic for the shiny new discussion forum.

**Comment by sneakywumpus** [comment]
All the macro examples that Fred posted in PR #164 do work (including the one that uses TYPE), so I think you can close this issue.

**Comment by sneakywumpus** [comment]
Another example:
The only line I needed to change in ex.mac is:
```
294c294
< 	.printx / Bit count of x is c /
---
> 	print	'/ Bit count of &X is &C /'
```

And it produces the same output as m80 when "bitcnt equ 1".
