### ISSUE TITLE
Implement complete ALU instructions for IX/L/H and IY/L/H

### ISSUE THREAD

**Issue by udo-munk** [udo-munk/z80pack#30]
Priority: low, the ones used by existing software are implemented
Difficulty: easy or difficult

Implementing the complete instruction block allows to enable the test for the instructions in the Z80 exerciser programs, and verify that everything is working correct.

Theoretially easy because it is mostly copy&paste work, but if the necessary changes are not done very pedantic it will be time consuming to find the bugs in the instructions. The exerciser programs are no help for finding out what is wrong. I have spend many nights in front of the emulation and a real Z80 machine to figure, why the emulation doesn't produce the same result as Zilog's silicon. This is no fun at all.

**Comment by EtchedPixels** [comment]
It's not entirely cut and paste - all the CB instructions with (IX+nn) do weird stuff

If you are looking at this can we get ED 70 and ED 71 implemented or will you take a patch for it ?

ED 70 writes 0 or 255 to an I/O port according to whether the CPU is NMOS or CMOS and there is code that uses this as a CPU type detect - plus I'd like to use it in Fuzix... ED 71 is IN F,(C) which throws away the input and just sets the flags  - again used in the odd bit of driver code.

I gave up on using exerciser programs directly with some other CPU emulation I was working on.I did what gets done with real systems - each instruction you capture (or dump) the full CPU state on both emulators (or emulator and real hardware) and then you collect the two together and a tool tells you straight away which instruction deviated and on what bits. Way way easier than sitting poking through CRC mismatches from Z80Test directly (which is so complete that an NEC 780 clone chip also fails).

The FUSE ZX Spectrum emulator is (timing aside due to wait states) pretty much a perfect emulation of a real Z80 if you need something to run code on and capture all the state easily. It has to be - the games abuse undocumented ops hard and the copy protection people used every trick including MEMPTR stuff.

AFAIK the only things it doesn't emulate correctly is the weirdness around SCF.

**Comment by udo-munk** [comment]
OK, those do wierd stuff and won't do with copy& paste. I meant the ones implemented for IX/L/H so far plus the few missing ones like SBC.

You can get any instruction you want, just provide a patch and I'll include it.
All I want is the feature that the undocumented ones compile conditionaly and can be excluded, and if included one still can trap on them with -i. That helps imensely with debugging runaway programs.

I know, I was involved with the exercisers a bit, see c.o.c discussions arround 95-96 or so. I was writing my own instruction tests, but when Frank come up with it, it was way more complete, only you won't find any bugs with this. At least he implemented the version not accounting the undocumented flags. Emulating them is a huge waste of CPU time for nothing, because the flags can't be used other than PUSH AF and then look at the stack memory. And then some Z80 clones also will fail such tests. If that was used for game copy protection, too bad.

**Comment by udo-munk** [comment]
And with regards to the NMOS/CMOS detection, probably it would be good too if the behaviour can be selected with a command line option?

**Comment by EtchedPixels** [comment]
Will take a look

**Comment by udo-munk** [comment]
Implemented ED 70/71.
In the IN F,(n) instruction I set the obvious flags and leave the others as they are,
I don't know how these are affected.

**Comment by sneakywumpus** [comment]
I've implemented full support (simulator/disassembler/assembler) for these instructions in pull  request #129 
Also corrects the implementation of ED 70/71

**Comment by EtchedPixels** [comment]
Yay... 8)

Will have to see if my cpu test still identifies it as emulator (very very few things pass 8))

**Comment by udo-munk** [comment]
Closing this issue because instruction set is complete now. Please create new issues for other failing tests.
