### ISSUE TITLE
Timing for interrupts

### ISSUE THREAD

**Issue by EtchedPixels** [udo-munk/z80pack#4]
Assuming I read the code right you don't account for interrupt delivery T states

I think something like this is needed for Z80 (and I don't know the 8080 timings)

[add_timing.txt](https://github.com/udo-munk/z80pack/files/1885342/add_timing.txt)

**Comment by udo-munk** [comment]
Thanks, added to dev.

Yep, I also don't know the 8080 timings, probably different, have to lookup this up in a 8080 datasheet.

In IM 0 any instruction can be put on the bus, correct, but nothing else than a call instruction would really work, because changing CPU state in an unexpected way for the main program.
Then I've never seen any TTL logic design to put a 3-byte call instruction on the bus during interrupt, much to complicated, so everyone sticked with using the 1-byte RST's. The CPU needs another error trap for this situation instead of executing RST 38 for unsupported bus data...
