### ISSUE TITLE
Documentation does not mention where website went?

### ISSUE THREAD

**Issue by ravn** [udo-munk/z80pack#439]
To my understanding z80pack had a very comprehensive web site with a lot of interesting disk images at https://www.autometer.de/unix4fun/z80pack/ which currently reports a 404 error

This repository does not have a README.md file which explains this, and that there is an archived version at https://web.archive.org/web/20240228161015/https://www.autometer.de/unix4fun/z80pack/  This could be useful for other casual drive-by users like me.

If the files still exist offline, it may be useful to migrate the site to live here on GitHub.   I have some experience with that and would be happy to help.

**Comment by udo-munk** [comment]
Autometer is a company of a friend, who hosted the z80pack web site. We are getting old, about to retire, and he had to serarate company and privat stuff, so it was removed there. The site now is hosted here: https://www.icl1900.co.uk/unix4fun/
I also thought about migrating it to GitHub because then it will last, but that is a lot of work probably and so far I had no time for this. Of course I have offline copies.

**Comment by udo-munk** [comment]
Put it into a Q/A discussions, so closing here.

**Comment by ravn** [comment]
I was unaware that you used Discussions.  I will continue there.

**Comment by ravn** [comment]
Hi again.

I have returned to z80pack in order to get your MP/M port to be the server side of a CP/NOS setup I am trying to get going.

I noticed that the new hosting site has gone too.   If you are interested, I would be willing to give the migration to github a try.

Thanks
/Thorbjørn
