### ISSUE TITLE
Add a revision number to the CP/M 2.2 BIOS (imsaisim)

### ISSUE THREAD

**Issue by dmcnaugh** [udo-munk/z80pack#69]
I know that space is getting tight in the CP/M 2.2 BIOS for the imsaisim, but...

I have been spending time lately supporting people who couldn't get the harddisk working or couldn't reach the SIO2 ports etc... 
It took me a while to ask the question "are you using the latest CP/M disk with the new BIOS
?" and some of them would ask "How would I know?"

Could you add a space a 'b' and 2 hex digits into the SIGNON banner after the `CP/M 2.2` to indicate the BIOS version, and bump this each time you release a new BIOS?

This would make it quicker and easier to know what BIOS people have on their system disk.
eg.
```
60K CP/M VER 2.2 b01
```
You can get 1 byte back by removing the 'S' from 'VERS' (as per the example above). The CP/M2.2 OS Manual only shows 'VER' (page 1-3). There is also some redundant code and data in the BIOS that "initialises" the SIOs, but in the emulation this is ignored.

**Comment by udo-munk** [comment]
Sorry for that, I did not expect so much active development and revisions, should have done that before.

I added a build number to the version string, which now is B01, so that it can be increased for further revisions.

If I remember right the string must be VERS for movcpm to work, I'll check on that later sometime when I get arround building a movcpm that includes the boot and bios code.
