### ISSUE TITLE
Request to Start Cromemco Emulator Fully From Command Line

### ISSUE THREAD

**Issue by cromemcos** [udo-munk/z80pack#82]
Currently I have used the Cromemco emulator, i.e. cromemcosim  binary  without error.

The call to the provided cromix script calls cromemcosim and this starts a Front Panel at which you need to set the start address to 0xc000, power on the machine, then press run on the front panel.

I would like a way to start the whole system from the command line, i.e. not to have to use the front panel at all.  This would allow scripted start and stop of the emulation etcetera.  Something that can't be done right now.

I had a look at the code and had hoped that removing the #ifdef FRONTPANEL and recompile would achieve this.  but not so simple!

So to achieve my request I would like either a way to run without the Frontpanel at all, or some way to programmatically feed the start address, power on and Run command into the started emulator  (with the front panel), so that overall the same thing, i.e. start without human interaction can be obtained.

thanks

m

**Comment by udo-munk** [comment]
This already is implemented for the IMSAI machine, which can be build without frontpanel and so it can be fully scripted without intervention. I'll implement this for the Cromemco machine also.

**Comment by udo-munk** [comment]
I have modified the sources to allow building a hedless system by commenting the FRONTPANEL define in sim.h. Building still generates a few warnings about unused variables/functions, which can be ignored, requires a few more #ifdef FRONTPANEL here and there.
The machine can be started with any of the RDOS ROM's, unfortunately it won't boot, the disk controller does't respond. I'm quite baffled, there must be an unkown issue in the FDC somewhere which likely is timing related, because this won't happen when the frontpanel LED's get updated.
For having a look you need to update your git clone and then checkout branch crodev, the not fully working code won't get merged into the master branch until everything working.

**Comment by udo-munk** [comment]
The headless system now boots, still have to enter CR into the terminal window for
baud rate detection.

**Comment by udo-munk** [comment]
Headless system can now boot without interventions with RDOS 2 & 3.
