### ISSUE TITLE
print_head(), print_reg(), ... are static?

### ISSUE THREAD

**Issue by litwr2** [udo-munk/z80pack#92]
IMHO they should not be static.  In previous releases they were not static.  This qualifier prevents do some tracing jobs outside monitor.  For instance, it is useful to write something like this
`if (PC == 0x200) print_reg();`

**Comment by udo-munk** [comment]
As far as I can remember these always have been static because internal implementation details of the ICE module, but lets see.
Booted a COHERENT 3.2 system from 1991 on QEMU, which has z80pack 1.6 installed, functions there already are declared static of course. And you won't have access to anything older than that. The COHERENT box is public available there: https://www.autometer.de/unix4fun/coherent/ftp/vms/

Of course one could argue to make these functions public, but you can do that anyway for your pupose. Instead one should implement hardware breakpoints in the ICE, as the Mostek devices had I was using back then and the ICE is modelled on that.

**Comment by litwr2** [comment]
Thank you.  Sorry I checked the modified release 1.28 - the original one has those functions static.
I use your z80sim in my software project [Z80 sorting](https://github.com/litwr2/Z80-sorting) and IMHO those functions are very useful as public for any software project.

**Comment by udo-munk** [comment]
I know what you mean. But instead of using questionable shortcuts you should learn how to use the In Circuit Emulator (ICE) that comes with the z80sim machine. With the trace command you can execute blocks of your sort routines including the register dump, to see what exactely it does.
Feel free to add any debbuging adds into you local copy, we all do this somethimes for analysis of unknown software, where sources are long lost. But for the release implementation I'll leave it as is, the functions are internals of the ICE and not some public interface for everyones usage. No physical existing ICE would let you do such things either.

**Comment by litwr2** [comment]
Thank you.  Indeed it is not much important because you allow us to modify your sources.  However let me ask a question.  I use data filling procedures written in C.  So I fill the Z80 RAM using these routines then I call your emulator from my C-code.  I don't normally use the monitor CLI.  How can the trace command help in this situation?  IMHO the fact that registers are public suggests that a routine that prints their value must be public too, etc.

**Comment by udo-munk** [comment]
That is easy, put a HALT instruction (0x76) into you code anywhere, if the CPU runs into the instruction it will stop and you'll get the ICE command line. Now you can single step, trace or continue to execute the code. For help with the ICE type ? at the command prompt.
No, the CPU registers should not be public, this is due to computing limitations I had in 1987 when I started to implement this. So far I have not had the time to refactor this, but as with any real CPU registers should not be public accessable, these of course are CPU internal.

**Comment by udo-munk** [comment]
Correct, the z80sim emulation is a Z80 CPU with 64KB RAM and a Mostek ICE, used to interactively test software. Not usefull for batch processing of course, that would require a different machine implementation.
So either you implement a new machine that does what you want and create a PR to have that included, or you also can create an Issue which describes detailed enough how that machine should be implemented, so that sometimes someone might inmplement it. In that machine also the needed logging of CPU internals can be implemented, that you need for your batch runs.
